export const PEIXES_CESTO = "PEIXES_CESTO";
export const JOGADA_PENDENTE = "JOGADA_PENDENTE";
export const MENSAGEM_PENDENTE = "MENSAGEM_PENDENTE";
export const RESULTADO_JOGADA = "RESULTADO_JOGADA";
